version: '3.8'

services:

# ------------------- MARIADB ------------------- #

  mariadb:

    image: mariadb:inception

    container_name: mariadb

    build:
      context: ./requirements/mariadb
      args:
        - UNIX_UID=$UNIX_UID
        - UNIX_GID=$UNIX_GID
        - MARIADB_VOLUME_LOCATION=$MARIADB_VOLUME_LOCATION

    volumes:
      - mariadb:/var/lib/mysql:rw

    env_file:
      - .env

    expose:
      - 3306

    networks:
      - inception_network

    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "--host=localhost"]
      start_period: 1m
      interval: 5s
      timeout: 2s
      retries: 21

    restart: unless-stopped

# ------------------ WORDPRESS ------------------ #

  wordpress:

    image: wordpress:inception

    container_name: wordpress

    build:
      context: ./requirements/wordpress
      args:
        - UNIX_UID=$UNIX_UID
        - UNIX_GID=$UNIX_GID
        - WP_VOLUME_LOCATION=$WP_VOLUME_LOCATION

    volumes:
      - wordpress:/var/www/wordpress:rw

    env_file:
      - .env

    expose:
      - 9000

    networks:
      - inception_network

    depends_on:
      mariadb:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "cgi-fcgi", "-connect", "localhost:9000", "/status"]
      start_period: 1m
      interval: 5s
      timeout: 2s
      retries: 21

    restart: unless-stopped

# -------------------- NGINX -------------------- #

  nginx:

    image: nginx:inception

    container_name: nginx

    build:
      context: ./requirements/nginx
      args:
        - UNIX_UID=$UNIX_UID
        - UNIX_GID=$UNIX_GID
        - NGINX_VOLUME_LOCATION=$NGINX_VOLUME_LOCATION

    volumes:
      - wordpress:/var/www/wordpress:rw

    env_file:
      - .env

    networks:
      - inception_network

    ports:
      - 443:443

    depends_on:
      wordpress:
        condition: service_healthy

    restart: unless-stopped

# ------------------- NETWORKS ------------------- #

networks:

  inception_network:

    name: inception_network
    driver: bridge

# ------------------- VOLUMES ------------------- #

volumes:

  wordpress:

    driver: local

    driver_opts:
      type: volume
      device: $HOME/data/vol_wordpress
      o: bind

  mariadb:

    driver: local

    driver_opts:
      type: volume
      device: $HOME/data/vol_mariadb
      o: bind
